### ISSUE TITLE
Compilation failed with -Werror=undef set for ARM GCC toolchain

### ISSUE THREAD

**Issue by leszek-grzegorek** [STMicroelectronics/cmsis_device_l5#2]
To avoid compilation error for toolchains like ARM GCC, etc. with -Werror=undef flag set, please find the proposed patch attached.
[stm32l552xx.h.patch.txt](https://github.com/STMicroelectronics/cmsis_device_l5/files/6936743/stm32l552xx.h.patch.txt)

**Comment by RKOUSTM** [comment]
Hi @leszek-grzegorek,

Thank you for your contribution.  An internal tracker has been logged and a fix will be implemented and made available in the frame of a future release.

Thank you once again for your contribution.

With regards,

**Comment by RKOUSTM** [comment]
ST Internal Reference: 111931
